# serverless.yml

service: check-rent

provider:
  name: aws
  region: eu-central-1
  versionFunctions: false
  layers:
    # Google Chrome for AWS Lambda as a layer
    # Make sure you use the latest version depending on the region
    # https://github.com/shelfio/chrome-aws-lambda-layer
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:10
  # function parameters
  runtime: nodejs12.x
  memorySize: 2048
  timeout: 30

functions:
  checkRent:
    handler: src/checkRent.handler
